In [1]:
import numpy as np

In [ ]:
# creating array using numpy
np.array([1,2,3,4,5])

In [ ]:
type(np.array([1,2,3,4,5]))

In [ ]:
np.array([1,2,3,4,5,"mani",4+8j])

In [ ]:
np.array([1,2,3,4,5,6.0])

In [ ]:
np.array([[1,3],[3,4]])

In [ ]:
np.array([[1,3],[3,4],[6,7,8]])

In [ ]:
np.array([[[1,3],[3,4]]])

In [ ]:
np.array([1,2,3],ndmin=3)

In [ ]:
np.array([1,2,3],dtype=complex)

In [ ]:
np.array([(1,2),(4,5)])

In [ ]:
# define different datatypes in the array
# <i2 ==> 16
# <i4 ==> 32
# <i8 ==> 64
# <i6 & <i16 ==> does not exists hence it will throw error 
arr=np.array([(1,2),(4,5)],dtype=[('a','<i2'),('b','<i8')])

In [ ]:
#arr=np.array([(1,2),(4,5)],dtype=[('a','<i2'),('b','<i6')])

In [ ]:
print(arr[0][0])
print(type(arr[0][0]))

In [ ]:
print(arr[0][1])
print(type(arr[0][1]))


In [5]:
arr=np.array([[1,3],[3,4]])

In [ ]:
arr

In [ ]:
arr[0][1]

In [ ]:
type(arr[0][1])

In [ ]:
# metrices
np.mat(arr)

In [ ]:
l=[3,4,5,6,7]

In [ ]:
np.array(l)

In [ ]:
np.asarray(l)

In [ ]:
np.asanyarray(l)

In [ ]:
mat=np.matrix(arr)

In [ ]:
np.asanyarray(mat)

In [ ]:
np.asarray(mat)

In [2]:
issubclass(np.matrix,np.ndarray)

True

In [3]:
issubclass(np.ndarray,np.matrix)

False

In [4]:
# Deep Copy and swallow copy

In [6]:
a=arr # Shallow copy

In [7]:
b=np.copy(arr) # Deep copy

In [8]:
arr[0][0]=67

In [9]:
arr

array([[67,  3],
       [ 3,  4]])

In [10]:
a

array([[67,  3],
       [ 3,  4]])

In [11]:
b

array([[1, 3],
       [3, 4]])

In [13]:
arr[0:10] # sclicing and indexing will work here as well

array([[67,  3],
       [ 3,  4]])

In [14]:
arr[-1]

array([3, 4])

In [16]:
for i in arr:
    print(i)
    print('======')

[67  3]
[3 4]


In [19]:
np.fromfunction(lambda i ,j :i==j,(4,4)) # here 4,4 represents rows and columns

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [18]:
type(np.fromfunction(lambda i ,j :i==j,(4,4)))

numpy.ndarray

In [21]:
np.fromfunction(lambda i ,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [22]:
np.fromfunction(lambda i ,j :i**j,(3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [23]:
np.fromfunction(lambda i ,j :i/j,(3,3))

<ipython-input-23-d8c7793bbd22>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i ,j :i/j,(3,3))
<ipython-input-23-d8c7793bbd22>:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i ,j :i/j,(3,3))


array([[nan, 0. , 0. ],
       [inf, 1. , 0.5],
       [inf, 2. , 1. ]])

In [24]:
[i * i for i in range(5)]

[0, 1, 4, 9, 16]

In [25]:
(i*i for i in range(5))

<generator object <genexpr> at 0x7fbfe356a350>

In [26]:
def test(x):
    yield x

In [27]:
test(5)

<generator object test at 0x7fbfe356a660>

In [32]:
gen=(i*i for i in range(5))

In [29]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [30]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [34]:
# need to initialize gen if already executed
for i in gen:
    print(i)

In [35]:
np.fromstring('1,34,5,6,6',sep=',',dtype=int)

array([ 1, 34,  5,  6,  6])

In [40]:
arr1=np.array([[[12,3,4],[2,3,4,5],[4,5,6,7]]])

<ipython-input-40-bc187929f595>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1=np.array([[[12,3,4],[2,3,4,5],[4,5,6,7]]])


In [41]:
arr1

array([[list([12, 3, 4]), list([2, 3, 4, 5]), list([4, 5, 6, 7])]],
      dtype=object)

In [42]:
arr1.ndim

2

In [43]:
arr1.size

3

In [44]:
arr1.shape

(1, 3)

In [45]:
arr1.dtype

dtype('O')